name: League of Legends Analysis Pipeline

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'config/summoners.json'

permissions:
  contents: write

jobs:
  analyze-summoners:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run LoL Analysis
      env:
        RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: python src/lol_analyzer.py
        
    - name: Generate Report
      run: python src/report_generator.py
        
    - name: Update README
      run: python src/update_readme.py
        
    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      with:
        name: lol-analysis-report
        path: reports/
        retention-days: 30
        
    - name: Commit and Push Results
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md reports/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update analysis reports [skip ci]"
        git push
