name: League of Legends Analysis Pipeline

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths: 
      - 'config/summoners.json'

jobs:
  analyze-summoners:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run LoL Analysis
      env:
        RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        python src/lol_analyzer.py
        
    - name: Generate Report
      run: |
        python src/report_generator.py
        
    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      with:
        name: lol-analysis-report
        path: |
          reports/
          *.json
          *.html
        retention-days: 30
        
    - name: Update README with Results
      run: |
        python src/update_readme.py
        
    - name: Commit Results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md reports/
        git diff --staged --quiet || git commit -m "🎮 Auto-update: League analysis $(date)"
        git push
